"""GENERATED ASSETS FOR THE HOSTED READER — the palette crosses the tree line once.

NL-163 Stage-A, milestone 2. Chartered by the engineering adjudication of
2026-08-29 §Q2: "the tokens/login shell are GENERATED from webui.TOKENS by a
product-tree script and drift-pinned by a suite test (a generated,
header-marked artifact is consumption, not a copy)."

WHY THIS MODULE EXISTS
----------------------
`hosted/` is a separate deployable with its own dependency story: it must not
import `newslens`, and its Docker image does not carry the product tree. So the
paper's palette has to reach it somehow, and there are exactly two ways: a
second table of hexes (drift, forbidden by DESIGN_SYSTEM.md), or a generated
artifact whose source is `webui.TOKENS` and whose staleness is a red test.

Everything this module emits is therefore DERIVED:

  * `tokens.css`        — webui.TOKENS verbatim + the shipped `body.dark`
                          inversion, both lifted out of webui by the same
                          extractor the bundle uses. The hosted shell's own CSS
                          then names nothing but `var(--…)`.
  * `manifest.webmanifest` — `background_color`/`theme_color` READ from the
                          token block. A manifest cannot hold a `var()`, so
                          this is one of the two places a hex must be spelled;
                          it is spelled by a program that read the source.
  * the icon C PNGs     — the principal's pick (DECISIONS 2026-08-29: "Icon =
                          C, the evening plate"), drawn from the same three
                          token values: ink ground, paper serif N, terra
                          underline. Rendered here rather than pasted in as
                          opaque bytes so the icon has provenance a reviewer
                          can re-run, and so a palette re-pin reaches the home
                          screen like it reaches everything else.

STDLIB ONLY (the product tree's three-dependency law): the PNG encoder is
`zlib` + `struct`, and the rasteriser below is ~80 lines of scanline coverage.
No image library, no font file, no network — `scripts/gen-hosted-assets`
reproduces every byte on a fresh clone.
"""

from __future__ import annotations

import json
import re
import struct
import zlib
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from . import paths, webui
from .editionbundle import _extract_block  # ONE extractor, not a second one

# The generated tree, relative to the repo root. `hosted/static/` is the Flask
# static dir; the Dockerfile copies it whole.
HOSTED_DIR_NAME = "hosted"
STATIC_DIR_NAME = "static"

GENERATED_MARKER = "GENERATED by scripts/gen-hosted-assets"

_TOKENS_HEADER = f"""/* ==========================================================================
   {GENERATED_MARKER} — DO NOT EDIT BY HAND.
   Source: src/newslens/webui.py (TOKENS + the shipped body.dark inversion).
   Regenerate:  scripts/gen-hosted-assets
   Drift is a suite failure (tests/test_nl163_push.py) — the hosted service
   consumes the paper's palette, it never keeps a second copy of it.
   ========================================================================== */
"""


def hosted_dir(root: Path = None) -> Path:
    return (root or paths.PROJECT_ROOT) / HOSTED_DIR_NAME


def static_dir(root: Path = None) -> Path:
    return hosted_dir(root) / STATIC_DIR_NAME


# ---------------------------------------------------------------------------
# The palette, read out of webui
# ---------------------------------------------------------------------------

def token(name: str, *, dark: bool = False) -> str:
    """One palette value, read from the shipped stylesheet.

    Same law and same extractor as `editionbundle.theme_colors` — the bundle
    needs two hexes for its `theme-color` metas and this module needs three for
    the icon; neither retypes them."""
    css = webui.CSS if dark else webui.TOKENS
    body = _extract_block(css, "body.dark" if dark else ":root")
    m = re.search(re.escape(name) + r"\s*:\s*(#[0-9A-Fa-f]{3,8})\s*;", body)
    if not m:
        raise RuntimeError(
            f"{name} not found in webui's {'body.dark' if dark else ':root'} "
            "block — the hosted palette is derived from it, never retyped")
    return m.group(1)


def render_tokens_css() -> str:
    """webui's token block plus its dark inversion, header-marked as generated."""
    dark_body = _extract_block(webui.CSS, "body.dark")
    return (
        _TOKENS_HEADER
        + webui.TOKENS.strip()
        + "\n\n/* The shipped mechanical inversion (webui.py) — the addendum §10\n"
          "   default is prefers-color-scheme; `body.dark` is the override class. */\n"
        + "body.dark {"
        + dark_body
        + "}\n"
    )


def render_manifest() -> str:
    """The PWA manifest (addendum §5: standalone, paper background, no splash).

    `_generated` is a comment in a format that has none: unknown members are
    ignored by the manifest parser, and a human opening the file learns where
    it came from before editing it by hand."""
    manifest = {
        "_generated": GENERATED_MARKER + " — edit src/newslens/hostedassets.py",
        "name": "NewsLens",
        "short_name": "NewsLens",
        "start_url": "/",
        "scope": "/",
        # §4 no-chrome, at the OS level: standalone is the frame the addendum's
        # safe-area law is written for.
        "display": "standalone",
        "orientation": "portrait",
        # §5 launch: "background = paper". No splash animation — the dateline
        # ceremony is the arrival.
        "background_color": token("--paper"),
        "theme_color": token("--paper"),
        "description": "The edition, frozen at publish.",
        "icons": [
            {"src": "/static/icon-192.png", "sizes": "192x192",
             "type": "image/png", "purpose": "any"},
            {"src": "/static/icon-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "any"},
            # Separate maskable entries: a maskable icon is drawn to survive a
            # circular mask (content inside the middle 80%), so it is a
            # DIFFERENT drawing, not the same file relabelled.
            {"src": "/static/icon-maskable-192.png", "sizes": "192x192",
             "type": "image/png", "purpose": "maskable"},
            {"src": "/static/icon-maskable-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "maskable"},
        ],
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# ICON C — "the evening plate" (his pick, DECISIONS 2026-08-29)
# ---------------------------------------------------------------------------
#
# The mockup's tile-c is: `background: #1A1713` with a Charter-bold "N" in
# `#FCFAF5` over a 3px `#8F4A2E` underline (mockup-phone-v1.html:186-189). A
# home-screen icon cannot ship as CSS, and it must not depend on a font file
# being present on the machine that builds it, so the letterform is drawn:
# two thin stems, a thick diagonal and four bracketed serifs — the transitional
# serif N the wordmark's face carries.
#
# GEOMETRY IN CAP-HEIGHT UNITS. Every number below is a fraction of the cap
# height H, so the same drawing rasterises at 32px and 512px without a second
# table. W is the stem-to-stem width; serifs overhang it by `SE` each side.

_W = 0.760      # glyph width, stem outer edge to stem outer edge
_SW = 0.135     # stem thickness (the thin strokes)
_DW = 0.225     # diagonal thickness, measured horizontally (the thick stroke)
_SE = 0.058     # serif overhang beyond a stem, each side
_ST = 0.058     # serif thickness

# The plate: cap height, the gap under the baseline, and the terra rule. Tuned
# against the mockup's own proportions at a 60px tile (34px type, 3px rule).
_CAP = 0.400            # cap height as a fraction of the icon edge
_RULE_GAP = 0.088       # baseline -> top of the rule
_RULE = 0.052           # rule thickness
# Maskable safe zone: the mask can be a circle of 80% diameter, so the whole
# drawing is scaled to sit inside it with room to spare.
_MASKABLE_SCALE = 0.74


class _Shape:
    """A convex piece of the drawing, as a y -> (x0, x1) span.

    Spans, not polygons, because every piece here is a rectangle or a
    parallelogram: the rasteriser then needs no winding rule, and the union of
    overlapping pieces is an interval merge instead of a self-intersection
    problem."""

    def __init__(self, y0: float, y1: float, x_at):
        self.y0, self.y1, self.x_at = y0, y1, x_at

    def span(self, y: float):
        if y < self.y0 or y >= self.y1:
            return None
        return self.x_at(y)


def _rect(x0, y0, x1, y1) -> _Shape:
    return _Shape(y0, y1, lambda y: (x0, x1))


def _glyph_shapes(x: float, y: float, cap: float) -> List[_Shape]:
    """The serif N, placed with its cap-top-left stem edge at (x, y)."""
    H = cap
    W, sw, dw, se, st = _W * H, _SW * H, _DW * H, _SE * H, _ST * H
    left, right, top, bottom = x, x + W, y, y + H
    return [
        _rect(left, top, left + sw, bottom),              # left stem
        _rect(right - sw, top, right, bottom),            # right stem
        # The diagonal: a parallelogram from the left stem's shoulder to the
        # right stem's foot — the thick stroke, as the face draws it.
        _Shape(top, bottom, lambda yy: (
            left + (yy - top) / H * (W - dw),
            left + (yy - top) / H * (W - dw) + dw)),
        _rect(left - se, top, left + sw + se, top + st),           # serifs
        _rect(left - se, bottom - st, left + sw + se, bottom),
        _rect(right - sw - se, top, right + se, top + st),
        _rect(right - sw - se, bottom - st, right + se, bottom),
    ]


def _coverage_rows(size: int, shapes: Sequence[_Shape], samples: int = 4):
    """Per-pixel coverage in [0,1] for the union of `shapes`.

    4x4 supersampling by span arithmetic: for each sub-scanline the shapes'
    x-intervals are merged (so an overlap is not counted twice) and each
    interval's horizontal coverage is added to the row, partial pixels
    included. This is what gives the letterform clean edges at 32px without a
    rendering library."""
    inv = 1.0 / samples
    weight = inv * inv
    for py in range(size):
        row = [0.0] * size
        for sy in range(samples):
            yy = py + (sy + 0.5) * inv
            spans = [s.span(yy) for s in shapes]
            spans = sorted(sp for sp in spans if sp is not None and sp[1] > sp[0])
            merged: List[List[float]] = []
            for x0, x1 in spans:
                if merged and x0 <= merged[-1][1]:
                    merged[-1][1] = max(merged[-1][1], x1)
                else:
                    merged.append([x0, x1])
            for x0, x1 in merged:
                x0 = max(0.0, x0)
                x1 = min(float(size), x1)
                if x1 <= x0:
                    continue
                first, last = int(x0), min(int(x1), size - 1)
                if first == last:
                    row[first] += (x1 - x0) * samples * weight
                    continue
                row[first] += (first + 1 - x0) * samples * weight
                for px in range(first + 1, last):
                    row[px] += samples * weight
                row[last] += (x1 - last) * samples * weight
        yield row


def _hex_rgb(value: str) -> Tuple[int, int, int]:
    v = value.lstrip("#")
    if len(v) == 3:
        v = "".join(c * 2 for c in v)
    return (int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16))


def _png(size: int, pixels: bytes) -> bytes:
    """A minimal 8-bit RGB PNG. Filter 0 on every scanline — the image is flat
    colour over a small drawing, so a filter search would buy nothing."""
    raw = b"".join(b"\x00" + pixels[y * size * 3:(y + 1) * size * 3]
                   for y in range(size))

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


def render_icon(size: int, *, maskable: bool = False) -> bytes:
    """Icon C at `size` px square, opaque (iOS composites no alpha anyway).

    Maskable draws the same plate smaller: the OS may crop to a circle of 80%
    diameter, and a mark that only survives the square is a mark that will be
    beheaded on somebody's home screen."""
    ink = _hex_rgb(token("--ink"))
    paper = _hex_rgb(token("--paper"))
    terra = _hex_rgb(token("--terra"))

    scale = _MASKABLE_SCALE if maskable else 1.0
    cap = _CAP * size * scale
    gap, rule = _RULE_GAP * size * scale, _RULE * size * scale
    glyph_w = (_W + 2 * _SE) * cap
    total_h = cap + gap + rule
    x0 = (size - glyph_w) / 2.0 + _SE * cap        # stem-left, not bbox-left
    y0 = (size - total_h) / 2.0

    letter = _glyph_shapes(x0, y0, cap)
    # The terra rule spans the letter's full width, serif overhang included —
    # the mockup draws it as the span's border-bottom, i.e. the text's width.
    underline = [_rect(x0 - _SE * cap, y0 + cap + gap,
                       x0 - _SE * cap + glyph_w, y0 + cap + gap + rule)]

    out = bytearray()
    letter_rows = _coverage_rows(size, letter)
    rule_rows = _coverage_rows(size, underline)
    for lrow, rrow in zip(letter_rows, rule_rows):
        for lc, rc in zip(lrow, rrow):
            lc = 0.0 if lc < 0 else (1.0 if lc > 1 else lc)
            rc = 0.0 if rc < 0 else (1.0 if rc > 1 else rc)
            for i in range(3):
                v = ink[i] + (paper[i] - ink[i]) * lc
                v = v + (terra[i] - v) * rc
                out.append(int(round(v)))
    return _png(size, bytes(out))


# ---------------------------------------------------------------------------
# The generated set
# ---------------------------------------------------------------------------
#
# One dict so `write_assets` and the drift pin cannot disagree about what is
# generated: the test regenerates this mapping and compares bytes on disk.

def render_boot_js() -> str:
    """The bundle's OWN boot script, shared with the shell pages.

    M1 gate, FIX-2's landing note: "M2's shell inherits BOOT_JS wholesale."
    The shell states (login, no-edition, archive) must resolve dark mode before
    first paint by the same three-state rule as an edition, and must carry the
    same touch-gated Dynamic Type seed — a second implementation would be a
    second dark-mode bug waiting to be found on one surface only."""
    from .editionbundle import BOOT_JS
    return (f"/* {GENERATED_MARKER} — DO NOT EDIT BY HAND.\n"
            "   Source: src/newslens/editionbundle.py (BOOT_JS), the same\n"
            "   script the frozen edition carries. Regenerate:\n"
            "   scripts/gen-hosted-assets */\n" + BOOT_JS.strip() + "\n")


def generated_assets() -> Dict[str, bytes]:
    out: Dict[str, bytes] = {
        "static/tokens.css": render_tokens_css().encode("utf-8"),
        "static/boot.js": render_boot_js().encode("utf-8"),
        "static/manifest.webmanifest": render_manifest().encode("utf-8"),
    }
    for size in (192, 512):
        out[f"static/icon-{size}.png"] = render_icon(size)
        out[f"static/icon-maskable-{size}.png"] = render_icon(size, maskable=True)
    # iOS ignores the manifest's icons for the home screen and reads this one.
    out["static/apple-touch-icon.png"] = render_icon(180)
    out["static/favicon.png"] = render_icon(48)
    return out


def stale_assets(root: Path = None) -> List[str]:
    """Generated files whose bytes on disk are not what this module produces."""
    base = hosted_dir(root)
    stale = []
    for rel, data in generated_assets().items():
        path = base / rel
        try:
            if path.read_bytes() != data:
                stale.append(rel)
        except OSError:
            stale.append(rel)
    return stale


def write_assets(root: Path = None) -> List[Tuple[str, bool]]:
    """Write every generated asset. Returns (path, changed) per file."""
    base = hosted_dir(root)
    written = []
    for rel, data in generated_assets().items():
        path = base / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        changed = True
        try:
            changed = path.read_bytes() != data
        except OSError:
            pass
        if changed:
            path.write_bytes(data)
        written.append((rel, changed))
    return written


def main(argv=None) -> int:
    paths.allow_real_paths()
    written = write_assets()
    for rel, changed in written:
        print(f"  {'wrote  ' if changed else 'current'} hosted/{rel}")
    n = sum(1 for _, changed in written if changed)
    print(f"{len(written)} generated assets · {n} changed · source: webui.TOKENS")
    return 0
